# Generated by Django 3.1.2 on 2021-09-11 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketInventory',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_settings.basemodel')),
                ('market_id', models.CharField(default='12912156', editable=False, max_length=255, verbose_name='Market ID')),
                ('cust_name', models.CharField(max_length=2255, verbose_name='Customer Name')),
                ('lot_code', models.IntegerField(verbose_name='Lot Code')),
                ('date_delivered', models.DateField(verbose_name='Date Delivered')),
            ],
            options={
                'verbose_name': 'Market Inventories',
                'verbose_name_plural': 'Market Inventories',
                'db_table': 'market_inventory',
            },
            bases=('base_settings.basemodel',),
        ),
    ]
