# Generated by Django 3.1.2 on 2021-09-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketinventory',
            name='market_id',
            field=models.CharField(default='73634337', editable=False, max_length=255, verbose_name='Market ID'),
        ),
    ]
