# Generated by Django 3.1.2 on 2021-09-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_inventory', '0002_auto_20210912_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketinventory',
            name='market_id',
            field=models.CharField(default='19737152', editable=False, max_length=255, verbose_name='Market ID'),
        ),
    ]
