# Generated by Django 3.2.6 on 2021-09-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_inventory', '0004_alter_marketinventory_market_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketinventory',
            name='market_id',
            field=models.CharField(default='95923622', editable=False, max_length=255, verbose_name='Market ID'),
        ),
    ]
