# Generated by Django 3.1.7 on 2021-09-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rice_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riceconsumed',
            name='rice_id',
            field=models.CharField(default='25719934', editable=False, max_length=255, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='riceinventory',
            name='rice_id',
            field=models.CharField(default='94379820', editable=False, max_length=255, verbose_name='ID'),
        ),
    ]
