# Generated by Django 3.1.2 on 2021-09-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rice_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riceconsumed',
            name='rice_id',
            field=models.CharField(default='33081363', editable=False, max_length=255, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='riceinventory',
            name='batch_no',
            field=models.CharField(max_length=255, verbose_name='RID'),
        ),
        migrations.AlterField(
            model_name='riceinventory',
            name='rice_id',
            field=models.CharField(default='12986772', editable=False, max_length=255, verbose_name='ID'),
        ),
    ]
