# Generated by Django 3.1.2 on 2021-09-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rice_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riceconsumed',
            name='rice_id',
            field=models.CharField(default='10234142', editable=False, max_length=255, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='riceinventory',
            name='rice_id',
            field=models.CharField(default='30848035', editable=False, max_length=255, verbose_name='ID'),
        ),
    ]
