# Generated by Django 3.1.2 on 2021-09-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rice_inventory', '0002_auto_20210912_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riceconsumed',
            name='rice_id',
            field=models.CharField(default='18352892', editable=False, max_length=255, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='riceinventory',
            name='rice_id',
            field=models.CharField(default='31498716', editable=False, max_length=255, verbose_name='ID'),
        ),
    ]
