# Generated by Django 3.1.2 on 2021-09-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rice_inventory', '0002_auto_20210912_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riceconsumed',
            name='rice_id',
            field=models.CharField(default='13122168', editable=False, max_length=255, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='riceinventory',
            name='rice_id',
            field=models.CharField(default='10119661', editable=False, max_length=255, verbose_name='ID'),
        ),
    ]
