# Generated by Django 3.1.7 on 2021-09-04 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rice_inventory', '0002_auto_20210904_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riceconsumed',
            name='inventory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rice_inventory', to='rice_inventory.riceinventory'),
        ),
        migrations.AlterField(
            model_name='riceconsumed',
            name='rice_id',
            field=models.CharField(default='31165573', editable=False, max_length=255, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='riceinventory',
            name='rice_id',
            field=models.CharField(default='14795691', editable=False, max_length=255, verbose_name='ID'),
        ),
    ]
