# Generated by Django 3.1.2 on 2021-09-11 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriedInventory',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_settings.basemodel')),
                ('batch_no', models.IntegerField(verbose_name='Batch No.')),
                ('date_fried', models.DateField(verbose_name='Date Fried/Packed')),
            ],
            options={
                'verbose_name': 'Fried Inventories',
                'verbose_name_plural': 'Fried Inventories',
            },
            bases=('base_settings.basemodel',),
        ),
    ]
