# Generated by Django 3.1.2 on 2021-09-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fried_inventory', '0002_auto_20210912_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='friedinventory',
            name='no_of_packs_15g',
            field=models.IntegerField(blank=True, null=True, verbose_name='No. of Packs (15g)'),
        ),
        migrations.AddField(
            model_name='friedinventory',
            name='no_of_packs_30g',
            field=models.IntegerField(blank=True, null=True, verbose_name='No. of Packs (30g)'),
        ),
    ]
