# Generated by Django 3.1.7 on 2021-09-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesame_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesameconsumed',
            name='sesame_id',
            field=models.CharField(default='11883224', editable=False, max_length=255, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sesameinventory',
            name='sesame_id',
            field=models.CharField(default='34910408', editable=False, max_length=255, verbose_name='ID'),
        ),
    ]
