# Generated by Django 3.1.2 on 2021-08-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongo_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mongoinventory',
            name='mongo_id',
            field=models.CharField(default='24126007', max_length=255, verbose_name='ID'),
        ),
    ]
