# Generated by Django 3.1.7 on 2021-09-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtruDateInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extru_id', models.CharField(default='30527423', editable=False, max_length=255, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=255, verbose_name='Batch No.')),
                ('date_produced', models.DateField(verbose_name='Date Produced')),
                ('total_volume', models.IntegerField(verbose_name='Total Volume (kg.)')),
                ('mongo_batch_no', models.CharField(max_length=255, verbose_name='Batch No. of Mongo')),
                ('rice_batch_no', models.CharField(max_length=255, verbose_name='Batch No. of Rice')),
                ('sesame_batch_no', models.CharField(max_length=255, verbose_name='Batch No. of Sesame')),
            ],
            options={
                'verbose_name': 'ExtruDates',
                'verbose_name_plural': 'ExtruDates',
            },
        ),
    ]
