# Generated by Django 3.2.6 on 2021-09-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrudate_inventory', '0004_alter_extrudateinventory_extru_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrudateinventory',
            name='extru_id',
            field=models.CharField(default='10714933', editable=False, max_length=255, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='extrudateinventory',
            table='extrudate_inventory',
        ),
    ]
