# Generated by Django 3.1.2 on 2021-09-11 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MongoInventory',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_settings.basemodel')),
                ('mongo_id', models.CharField(default='46599171', editable=False, max_length=255, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=255, verbose_name='Batch No.')),
                ('date_received', models.DateField(verbose_name='Date Received')),
                ('total_avail_volume', models.IntegerField(verbose_name='Total Available Volume')),
            ],
            options={
                'verbose_name': 'Mongo Inventory',
                'verbose_name_plural': 'Mongo Inventories',
                'db_table': 'mongo_inventory',
            },
            bases=('base_settings.basemodel',),
        ),
        migrations.CreateModel(
            name='MongoConsumed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mongo_id', models.CharField(default='46600003', editable=False, max_length=255, verbose_name='ID')),
                ('total_avail_volume', models.IntegerField(verbose_name='Total Available Volume')),
                ('amount_consumed', models.IntegerField(blank=True, null=True, verbose_name='Amount Consumed')),
                ('date_consumed', models.DateField(blank=True, null=True, verbose_name='Date Consumed')),
                ('inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mongo_inventory', to='mongo_inventory.mongoinventory')),
            ],
            options={
                'verbose_name': 'Mongo Consumed',
                'verbose_name_plural': 'Mongo Consumed',
                'db_table': 'mongo_consumed',
            },
        ),
    ]
