# Generated by Django 3.1.2 on 2021-08-29 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MongoInventory',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_settings.basemodel')),
                ('batch_no', models.CharField(max_length=255, verbose_name='Batch No.')),
                ('date_received', models.DateField(verbose_name='Date Received')),
                ('total_avail_volume', models.IntegerField(verbose_name='Total Available Volume')),
                ('amount_consumed', models.IntegerField(blank=True, null=True, verbose_name='Amount Consumed')),
                ('date_consumed', models.DateField(blank=True, null=True, verbose_name='Date Consumed')),
            ],
            options={
                'verbose_name': 'Mongo Inventory',
                'verbose_name_plural': 'Mongo Inventories',
            },
            bases=('base_settings.basemodel',),
        ),
    ]
