# Generated by Django 3.1.2 on 2021-08-30 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongo_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mongoconsumed',
            name='mongo_id',
            field=models.CharField(default='17188328', editable=False, max_length=255, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mongoinventory',
            name='mongo_id',
            field=models.CharField(default='17007944', editable=False, max_length=255, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='mongoconsumed',
            table='mongo_consumed',
        ),
        migrations.AlterModelTable(
            name='mongoinventory',
            table='mongo_inventory',
        ),
    ]
