# Generated by Django 3.1.2 on 2021-09-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongo_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mongoconsumed',
            name='mongo_id',
            field=models.CharField(default='93699286', editable=False, max_length=255, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mongoinventory',
            name='mongo_id',
            field=models.CharField(default='22099297', editable=False, max_length=255, verbose_name='ID'),
        ),
    ]
