# Generated by Django 3.1.2 on 2021-08-30 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mongo_inventory', '0002_auto_20210831_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mongoconsumed',
            name='inventory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mongo_inventory', to='mongo_inventory.mongoinventory'),
        ),
        migrations.AlterField(
            model_name='mongoconsumed',
            name='mongo_id',
            field=models.CharField(default='12193816', editable=False, max_length=255, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mongoinventory',
            name='mongo_id',
            field=models.CharField(default='15971590', editable=False, max_length=255, verbose_name='ID'),
        ),
    ]
