# Generated by Django 3.1.2 on 2021-09-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongo_inventory', '0003_auto_20210912_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mongoconsumed',
            name='mongo_id',
            field=models.CharField(default='15988849', editable=False, max_length=255, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mongoinventory',
            name='mongo_id',
            field=models.CharField(default='13614935', editable=False, max_length=255, verbose_name='ID'),
        ),
    ]
