# Generated by Django 3.1.2 on 2021-08-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongo_inventory', '0003_auto_20210831_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='mongoconsumed',
            name='total_avail_volume',
            field=models.IntegerField(default=1, verbose_name='Total Available Volume'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mongoconsumed',
            name='mongo_id',
            field=models.CharField(default='24351988', editable=False, max_length=255, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mongoinventory',
            name='mongo_id',
            field=models.CharField(default='28160304', editable=False, max_length=255, verbose_name='ID'),
        ),
    ]
