# Generated by Django 3.1.7 on 2021-09-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongo_inventory', '0006_auto_20210904_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mongoconsumed',
            name='mongo_id',
            field=models.CharField(default='17763693', editable=False, max_length=255, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mongoinventory',
            name='mongo_id',
            field=models.CharField(default='93803757', editable=False, max_length=255, verbose_name='ID'),
        ),
    ]
