# Generated by Django 3.2.6 on 2021-09-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
