# Generated by Django 3.1.2 on 2021-09-11 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlavouringsInventory',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_settings.basemodel')),
                ('flavourings_id', models.CharField(default='20715627', editable=False, max_length=255, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=255, verbose_name='Batch No.')),
                ('date_received', models.DateField(verbose_name='Date Received')),
                ('total_avail_volume', models.IntegerField(verbose_name='Total Available Volume')),
                ('flavourings', models.CharField(max_length=255, verbose_name='Flavourings')),
            ],
            options={
                'verbose_name': 'Flavourings Inventories',
                'verbose_name_plural': 'Flavourings Inventories',
                'db_table': 'flavourings_inventory',
            },
            bases=('base_settings.basemodel',),
        ),
        migrations.CreateModel(
            name='FlavouringsConsumed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavourings_id', models.CharField(default='28410995', editable=False, max_length=255, verbose_name='ID')),
                ('total_avail_volume', models.IntegerField(verbose_name='Total Available Volume')),
                ('amount_consumed', models.IntegerField(blank=True, null=True, verbose_name='Amount Consumed')),
                ('date_consumed', models.DateField(blank=True, null=True, verbose_name='Date Consumed')),
                ('inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavourings_inventory', to='flavourings_inventory.flavouringsinventory')),
            ],
            options={
                'verbose_name': 'Flavourings Consumed',
                'verbose_name_plural': 'Flavourings Consumed',
                'db_table': 'flavourings_consumed',
            },
        ),
    ]
