# Generated by Django 3.1.2 on 2021-09-11 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flavourings_inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlavouringsConsumed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavourings_id', models.CharField(default='63424956', editable=False, max_length=255, verbose_name='ID')),
                ('total_avail_volume', models.IntegerField(verbose_name='Total Available Volume')),
                ('amount_consumed', models.IntegerField(blank=True, null=True, verbose_name='Amount Consumed')),
                ('date_consumed', models.DateField(blank=True, null=True, verbose_name='Date Consumed')),
            ],
            options={
                'verbose_name': 'Flavourings Consumed',
                'verbose_name_plural': 'Flavourings Consumed',
                'db_table': 'flavourings_consumed',
            },
        ),
        migrations.AlterField(
            model_name='flavouringsinventory',
            name='flavourings_id',
            field=models.CharField(default='47420104', editable=False, max_length=255, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='FilmoraConsumed',
        ),
        migrations.AddField(
            model_name='flavouringsconsumed',
            name='inventory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavourings_inventory', to='flavourings_inventory.flavouringsinventory'),
        ),
    ]
